# Municipal Analysis: Infrastructure and Tourism Density

In [1]:
import pandas as pd
from pathlib import Path

In [3]:
import pandas as pd
from pathlib import Path

data_dir = Path("..") / "data"

beds_df = pd.read_csv(data_dir / "accommodation_beds.csv", sep=";", encoding="latin1")
roads_df = pd.read_csv(data_dir / "road_lengths.csv", sep=";", encoding="latin1")
area_df = pd.read_csv(data_dir / "municipalities_area.csv", sep=";", encoding="latin1")

beds_df.head()

                                  ï»¿"117s -- Majoitusliikkeiden kapasiteetti kunnittain, 1995-2025"
Kunta     Majoitusliikkeen tyyppi                                  Vuoteet, lkm 2023
KOKO MAA  Kaikki majoitusliikkeet                                             185560
Akaa      Kaikki majoitusliikkeet                                                  .
AlajÃ¤rvi Kaikki majoitusliikkeet                                                  .
Alavieska Kaikki majoitusliikkeet                                                  .

In [ ]:
beds_df.columns = beds_df.columns.str.strip()

beds_df.columns

Index(['ï»¿"117s -- Majoitusliikkeiden kapasiteetti kunnittain, 1995-2025"'], dtype='str')

In [ ]:
from pathlib import Path
import pandas as pd

data_dir = Path("..") / "data"

beds_df = pd.read_csv(
    data_dir / "accommodation_beds.csv",
    sep=";",          
    encoding="latin1",
    skiprows=1       
)

print("Sarakkeet:", beds_df.columns.tolist())
beds_df.head()

Sarakkeet: ['Kunta', 'Majoitusliikkeen tyyppi', 'Vuoteet, lkm 2023']

       Kunta  Majoitusliikkeen tyyppi Vuoteet, lkm 2023
0   KOKO MAA  Kaikki majoitusliikkeet            185560
1       Akaa  Kaikki majoitusliikkeet                 .
2  AlajÃ¤rvi  Kaikki majoitusliikkeet                 .
3  Alavieska  Kaikki majoitusliikkeet                 .
4     Alavus  Kaikki majoitusliikkeet               364

In [28]:
# Ladataan roads-data uudestaan puhtaasti
roads_df = pd.read_csv(
    data_dir / "road_lengths.csv",
    sep=";",
    encoding="latin1",
    skiprows=1
)

print("Sarakkeet:", roads_df.columns.tolist())
print("Vuosi unique:", roads_df["Vuosi"].unique()[:5])

Sarakkeet: ['Alue', 'Tieluokka', 'Päällyste', 'Vuosi', 'Tiepituus']
Vuosi unique: [2023]

In [29]:
# Valitaan vuosi 2023 (stringinä varmuuden vuoksi)
roads_2023 = roads_df[roads_df["Vuosi"] == "2023"].copy()

# Poistetaan KOKO MAA
roads_2023 = roads_2023[roads_2023["Alue"] != "KOKO MAA"].copy()

# Otetaan tarvittavat sarakkeet
roads_2023 = roads_2023[["Alue", "Tiepituus"]].copy()

# Nimetään selkeästi
roads_2023 = roads_2023.rename(columns={
    "Alue": "municipality",
    "Tiepituus": "road_km"
})

# Muutetaan numeroksi
roads_2023["road_km"] = pd.to_numeric(roads_2023["road_km"], errors="coerce")

roads_2023.head()

Empty DataFrame
Columns: [municipality, road_km]
Index: []

In [30]:
# Ladataan pinta-aladata
area_df = pd.read_csv(
    data_dir / "municipalities_area.csv",
    sep=";",
    encoding="latin1",
    skiprows=1
)

print("Sarakkeet:", area_df.columns.tolist())
area_df.head()

Sarakkeet: ['Alue', 'Tiedot', '2023']

        Alue             Tiedot       2023
0   KOKO MAA  Maapinta-ala, km²  303610.99
1       Akaa  Maapinta-ala, km²     293.27
2   Alajärvi  Maapinta-ala, km²    1008.85
3  Alavieska  Maapinta-ala, km²     251.54
4     Alavus  Maapinta-ala, km²    1087.18

In [32]:
print(area_df.columns.tolist())

['Alue', 'Tiedot', '2023']

In [33]:
# Poistetaan KOKO MAA
area_df = area_df[area_df["Alue"] != "KOKO MAA"].copy()

# Otetaan vain kunta + vuoden 2023 arvo
area_df = area_df[["Alue", "2023"]].copy()

# Nimetään selkeästi
area_df = area_df.rename(columns={
    "Alue": "municipality",
    "2023": "area_km2"
})

# Muutetaan numeroksi
area_df["area_km2"] = (
    area_df["area_km2"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

area_df.head()

  municipality  area_km2
1         Akaa    293.27
2     Alajärvi   1008.85
3    Alavieska    251.54
4       Alavus   1087.18
5     Asikkala    563.41